version: '3.2'

services:
   imagebuild:
     build:
       args:
         IMAGE_ARCH: arm64v8
         QEMU_FILE: qemu-aarch64-static
         RUN_CMD: chmod +x /input/main.sh && /input/main.sh arm64
